// <auto-generated />
using System;
using ChatRoomBackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChatRoomBackEnd.Migrations
{
    [DbContext(typeof(ChatRoomDBContext))]
    [Migration("20220128232454_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChatRoomBackEnd.Data.Entities.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserName");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("ChatRoomBackEnd.Data.Entities.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChatRoomBackEnd.Data.Entities.Chat", b =>
                {
                    b.HasOne("ChatRoomBackEnd.Data.Entities.User", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserName");
                });
#pragma warning restore 612, 618
        }
    }
}
